
exports.seed = function (knex, Promise) {
  // Deletes ALL existing entries
  return knex('articles').del()
    .then(function () {
      // Inserts seed entries
      return knex('articles').insert([
        {
          "id": 13,
          "heading": "Tips for Becoming a Design Leader",
          "description": "One of the things I love about working at Facebook is the emphasis we put on personal growth and the objectives people have for their careers...",
          "content": "One of the things I love about working at Facebook is the emphasis we put on personal growth and the objectives people have for their careers...",
          "backdrop": "https:\/\/facebook.design\/public\/images\/designing-against-misinformation.png",
          "user_id": 1,
          "category_id": 1,
          "created_at": "2018-12-09T09:18:07Z",
          "modified_date": null,
          "status": true,
          "slug": "tips-for-becoming-a-design-leader"
        },
        {
          "id": 10,
          "heading": "Evolving the Facebook News Feed to Serve You Better",
          "description": "Evolving the Facebook News Feed to Serve You Better",
          "content": "Evolving the Facebook News Feed to Serve You Better",
          "backdrop": "https:\/\/facebook.design\/public\/images\/evolving_the_facebook_news_feed_to_serve_you_better.jpg",
          "user_id": 1,
          "category_id": 1,
          "created_at": "2018-12-09T09:18:07Z",
          "modified_date": null,
          "status": true,
          "slug": "evolving-the-facebook-news-feed-to-serve-you-better"
        },
        {
          "id": 12,
          "heading": "Questions to Ask as a New Designer on the Team",
          "description": "Last summer I switched teams at Facebook. My first project seemed simple enough: redesign the sign up flow for Facebook Lite, an app for low-end Android phones.",
          "content": "Last summer I switched teams at Facebook. My first project seemed simple enough: redesign the sign up flow for Facebook Lite, an app for low-end Android phones.",
          "backdrop": "https:\/\/facebook.design\/public\/images\/questions-to-ask-as-a-new-designer-on-the-team.png",
          "user_id": 1,
          "category_id": 1,
          "created_at": "2018-12-09T09:18:07Z",
          "modified_date": null,
          "status": true,
          "slug": "questions-to-ask-as-a-new-designer-on-the-team"
        },
        {
          "id": 2,
          "heading": "Hear, There, and Everywhere",
          "description": "Facebook Design in conversation with co-authors Fuchsia MacAree and Scott Boms on their book and the importance of listening",
          "content": "Facebook Design in conversation with co-authors Fuchsia MacAree and Scott Boms on their book and the importance of listening",
          "backdrop": "https:\/\/facebook.design\/public\/images\/hear-there-and-everywhere.png",
          "user_id": 1,
          "category_id": 1,
          "created_at": "2018-12-09T09:18:07Z",
          "modified_date": null,
          "status": true,
          "slug": "hear-there-and-everywhere"
        },
        {
          "id": 3,
          "heading": "An Unforgettable Valentine’s Day",
          "description": "A product design intern’s resource for design students and romantics",
          "content": "A product design intern’s resource for design students and romantics",
          "backdrop": "https:\/\/facebook.design\/public\/images\/an-unforgettable-valentines-day.png",
          "user_id": 1,
          "category_id": 1,
          "created_at": "2018-12-09T09:18:07Z",
          "modified_date": null,
          "status": true,
          "slug": "an-unforgettable-valentines-day"
        },
        {
          "id": 4,
          "heading": "Able, Allowed, Should; Navigating Modern Tech Ethics",
          "description": "I want to share a talk I gave on the design track at SXSW in early March of this year. This talk was inspired by a deeply held belief that we are at a critical time in my company...",
          "content": "I want to share a talk I gave on the design track at SXSW in early March of this year. This talk was inspired by a deeply held belief that we are at a critical time in my company...",
          "backdrop": "https:\/\/facebook.design\/public\/images\/able-allowed-should-navigating-modern-tech-ethics.png",
          "user_id": 1,
          "category_id": 1,
          "created_at": "2018-12-09T09:18:07Z",
          "modified_date": null,
          "status": true,
          "slug": "able-allowed-should-navigating-modern-tech-ethics"
        },
        {
          "id": 5,
          "heading": "Designing New Ways to Give Context to News Stories",
          "description": "When scrolling through News Feed, it’s sometimes difficult to judge the credibility of an article. As with all information on the internet, if we’re unfamiliar with an article’s source...",
          "content": "When scrolling through News Feed, it’s sometimes difficult to judge the credibility of an article. As with all information on the internet, if we’re unfamiliar with an article’s source...",
          "backdrop": "https:\/\/facebook.design\/public\/images\/designing-new-ways-to-give-context-to-news-stories.png",
          "user_id": 1,
          "category_id": 1,
          "created_at": "2018-12-09T09:18:07Z",
          "modified_date": null,
          "status": true,
          "slug": "designing-new-ways-to-give-context-to-news-stories"
        },
        {
          "id": 6,
          "heading": "Meditation and Design at Facebook",
          "description": "How does a routine meditation practice benefit us as designers? What is it about Facebook that creates an environment that encourages meditation and mindfulness? And how can other companies do the same?",
          "content": "How does a routine meditation practice benefit us as designers? What is it about Facebook that creates an environment that encourages meditation and mindfulness? And how can other companies do the same?",
          "backdrop": "https:\/\/facebook.design\/public\/images\/meditation-and-design-at-facebook.png",
          "user_id": 1,
          "category_id": 1,
          "created_at": "2018-12-09T09:18:07Z",
          "modified_date": null,
          "status": true,
          "slug": "meditation-and-design-at-facebook"
        },
        {
          "id": 7,
          "heading": "Designing Against Misinformation",
          "description": "Scrolling through News Feed, it can be hard to judge what stories are true or false. Should you trust everything that you see, even if it comes from someone whom you don’t know well?... ",
          "content": "Scrolling through News Feed, it can be hard to judge what stories are true or false. Should you trust everything that you see, even if it comes from someone whom you don’t know well?... ",
          "backdrop": "https:\/\/facebook.design\/public\/images\/designing-against-misinformation.png",
          "user_id": 1,
          "category_id": 1,
          "created_at": "2018-12-09T09:18:07Z",
          "modified_date": null,
          "status": true,
          "slug": "designing-against-misinformation"
        },
        {
          "id": 8,
          "heading": "The Enterprising Designer: Beyond Consumer Product Design",
          "description": "Which is better: A career in consumer product design or a career in enterprise product design?",
          "content": "Which is better: A career in consumer product design or a career in enterprise product design?",
          "backdrop": "https:\/\/facebook.design\/public\/images\/the-enterprising-designer-beyond-consumer-product-design.png",
          "user_id": 1,
          "category_id": 1,
          "created_at": "2018-12-09T09:18:07Z",
          "modified_date": null,
          "status": true,
          "slug": "the-enterprising-designer-beyond-consumer-product-design"
        },
        {
          "id": 9,
          "heading": "One Year Designing at WhatsApp",
          "description": "Thoughts on how WhatsApp and Facebook design at scale",
          "content": "Thoughts on how WhatsApp and Facebook design at scale",
          "backdrop": "https:\/\/facebook.design\/public\/images\/one-year-designing-at-whatsapp.png",
          "user_id": 1,
          "category_id": 1,
          "created_at": "2018-12-09T09:18:07Z",
          "modified_date": null,
          "status": true,
          "slug": "one-year-designing-at-whatsapp"
        },
        {
          "id": 11,
          "heading": "How to Enhance Mobile Interactions with Sound Design",
          "description": "When I talk to people about sound design and the role it plays at Facebook, many people seem puzzled at first. “Sound? Facebook?”...",
          "content": "When I talk to people about sound design and the role it plays at Facebook, many people seem puzzled at first. “Sound? Facebook?”...",
          "backdrop": "https:\/\/facebook.design\/public\/images\/sound-design-and-enhancing-mobile-interactions-at-facebook.jpg",
          "user_id": 1,
          "category_id": 1,
          "created_at": "2018-12-09T09:18:07Z",
          "modified_date": null,
          "status": true,
          "slug": "how-to-enhance-mobile-interactions-with-sound-design"
        },
        {
          "id": 17,
          "heading": "Tips for Becoming a Design Leader",
          "description": "One of the things I love about working at Facebook is the emphasis we put on personal growth and the objectives people have for their careers...",
          "content": "One of the things I love about working at Facebook is the emphasis we put on personal growth and the objectives people have for their careers...",
          "backdrop": "https:\/\/facebook.design\/public\/images\/designing-new-ways-to-give-context-to-news-stories.png",
          "user_id": 1,
          "category_id": 1,
          "created_at": "2018-12-09T09:18:07Z",
          "modified_date": null,
          "status": true,
          "slug": "tips-for-becoming-a-design-leader"
        },
        {
          "id": 28,
          "heading": "Tips for Becoming a Design Leader",
          "description": "One of the things I love about working at Facebook is the emphasis we put on personal growth and the objectives people have for their careers...",
          "content": "One of the things I love about working at Facebook is the emphasis we put on personal growth and the objectives people have for their careers...",
          "backdrop": "https:\/\/facebook.design\/public\/images\/designing-against-misinformation.png",
          "user_id": 1,
          "category_id": 1,
          "created_at": "2018-12-09T09:18:07Z",
          "modified_date": null,
          "status": true,
          "slug": "tips-for-becoming-a-design-leader"
        },
        {
          "id": 24,
          "heading": "One Year Designing at WhatsApp",
          "description": "Thoughts on how WhatsApp and Facebook design at scale",
          "content": "Thoughts on how WhatsApp and Facebook design at scale",
          "backdrop": "https:\/\/facebook.design\/public\/images\/one-year-designing-at-whatsapp.png",
          "user_id": 1,
          "category_id": 1,
          "created_at": "2018-12-09T09:18:07Z",
          "modified_date": null,
          "status": true,
          "slug": "one-year-designing-at-whatsapp"
        },
        {
          "id": 19,
          "heading": "Able, Allowed, Should; Navigating Modern Tech Ethics",
          "description": "I want to share a talk I gave on the design track at SXSW in early March of this year. This talk was inspired by a deeply held belief that we are at a critical time in my company...",
          "content": "I want to share a talk I gave on the design track at SXSW in early March of this year. This talk was inspired by a deeply held belief that we are at a critical time in my company...",
          "backdrop": "https:\/\/facebook.design\/public\/images\/able-allowed-should-navigating-modern-tech-ethics.png",
          "user_id": 1,
          "category_id": 1,
          "created_at": "2018-12-09T09:18:07Z",
          "modified_date": null,
          "status": true,
          "slug": "able-allowed-should-navigating-modern-tech-ethics"
        },
        {
          "id": 20,
          "heading": "Designing New Ways to Give Context to News Stories",
          "description": "When scrolling through News Feed, it’s sometimes difficult to judge the credibility of an article. As with all information on the internet, if we’re unfamiliar with an article’s source...",
          "content": "When scrolling through News Feed, it’s sometimes difficult to judge the credibility of an article. As with all information on the internet, if we’re unfamiliar with an article’s source...",
          "backdrop": "https:\/\/facebook.design\/public\/images\/designing-new-ways-to-give-context-to-news-stories.png",
          "user_id": 1,
          "category_id": 1,
          "created_at": "2018-12-09T09:18:07Z",
          "modified_date": null,
          "status": true,
          "slug": "designing-new-ways-to-give-context-to-news-stories"
        },
        {
          "id": 21,
          "heading": "Meditation and Design at Facebook",
          "description": "How does a routine meditation practice benefit us as designers? What is it about Facebook that creates an environment that encourages meditation and mindfulness? And how can other companies do the same?",
          "content": "How does a routine meditation practice benefit us as designers? What is it about Facebook that creates an environment that encourages meditation and mindfulness? And how can other companies do the same?",
          "backdrop": "https:\/\/facebook.design\/public\/images\/meditation-and-design-at-facebook.png",
          "user_id": 1,
          "category_id": 1,
          "created_at": "2018-12-09T09:18:07Z",
          "modified_date": null,
          "status": true,
          "slug": "meditation-and-design-at-facebook"
        },
        {
          "id": 22,
          "heading": "Designing Against Misinformation",
          "description": "Scrolling through News Feed, it can be hard to judge what stories are true or false. Should you trust everything that you see, even if it comes from someone whom you don’t know well?... ",
          "content": "Scrolling through News Feed, it can be hard to judge what stories are true or false. Should you trust everything that you see, even if it comes from someone whom you don’t know well?... ",
          "backdrop": "https:\/\/facebook.design\/public\/images\/designing-against-misinformation.png",
          "user_id": 1,
          "category_id": 1,
          "created_at": "2018-12-09T09:18:07Z",
          "modified_date": null,
          "status": true,
          "slug": "designing-against-misinformation"
        },
        {
          "id": 23,
          "heading": "The Enterprising Designer: Beyond Consumer Product Design",
          "description": "Which is better: A career in consumer product design or a career in enterprise product design?",
          "content": "Which is better: A career in consumer product design or a career in enterprise product design?",
          "backdrop": "https:\/\/facebook.design\/public\/images\/the-enterprising-designer-beyond-consumer-product-design.png",
          "user_id": 1,
          "category_id": 1,
          "created_at": "2018-12-09T09:18:07Z",
          "modified_date": null,
          "status": true,
          "slug": "the-enterprising-designer-beyond-consumer-product-design"
        },
        {
          "id": 25,
          "heading": "Evolving the Facebook News Feed to Serve You Better",
          "description": "Evolving the Facebook News Feed to Serve You Better",
          "content": "Evolving the Facebook News Feed to Serve You Better",
          "backdrop": "https:\/\/facebook.design\/public\/images\/evolving_the_facebook_news_feed_to_serve_you_better.jpg",
          "user_id": 1,
          "category_id": 1,
          "created_at": "2018-12-09T09:18:07Z",
          "modified_date": null,
          "status": true,
          "slug": "evolving-the-facebook-news-feed-to-serve-you-better"
        },
        {
          "id": 26,
          "heading": "How to Enhance Mobile Interactions with Sound Design",
          "description": "When I talk to people about sound design and the role it plays at Facebook, many people seem puzzled at first. “Sound? Facebook?”...",
          "content": "When I talk to people about sound design and the role it plays at Facebook, many people seem puzzled at first. “Sound? Facebook?”...",
          "backdrop": "https:\/\/facebook.design\/public\/images\/sound-design-and-enhancing-mobile-interactions-at-facebook.jpg",
          "user_id": 1,
          "category_id": 1,
          "created_at": "2018-12-09T09:18:07Z",
          "modified_date": null,
          "status": true,
          "slug": "how-to-enhance-mobile-interactions-with-sound-design"
        },
        {
          "id": 27,
          "heading": "Questions to Ask as a New Designer on the Team",
          "description": "Last summer I switched teams at Facebook. My first project seemed simple enough: redesign the sign up flow for Facebook Lite, an app for low-end Android phones.",
          "content": "Last summer I switched teams at Facebook. My first project seemed simple enough: redesign the sign up flow for Facebook Lite, an app for low-end Android phones.",
          "backdrop": "https:\/\/facebook.design\/public\/images\/questions-to-ask-as-a-new-designer-on-the-team.png",
          "user_id": 1,
          "category_id": 1,
          "created_at": "2018-12-09T09:18:07Z",
          "modified_date": null,
          "status": true,
          "slug": "questions-to-ask-as-a-new-designer-on-the-team"
        },
        {
          "id": 29,
          "heading": "Hear, There, and Everywhere",
          "description": "Facebook Design in conversation with co-authors Fuchsia MacAree and Scott Boms on their book and the importance of listening",
          "content": "Facebook Design in conversation with co-authors Fuchsia MacAree and Scott Boms on their book and the importance of listening",
          "backdrop": "https:\/\/facebook.design\/public\/images\/hear-there-and-everywhere.png",
          "user_id": 1,
          "category_id": 1,
          "created_at": "2018-12-09T09:18:07Z",
          "modified_date": null,
          "status": true,
          "slug": "hear-there-and-everywhere"
        },
        {
          "id": 18,
          "heading": "An Unforgettable Valentine’s Day",
          "description": "A product design intern’s resource for design students and romantics",
          "content": "<p>\n          Holy grail funding non-disclosure agreement advisor ramen bootstrapping ecosystem. Beta crowdfunding iteration assets business\n          plan paradigm shift stealth mass market seed money rockstar niche market marketing buzz market.\n        <\/p>\n        <p>\n          Burn rate release facebook termsheet equity technology. Interaction design rockstar network effects handshake creative startup\n          direct mailing. Technology influencer direct mailing deployment return on investment seed round.\n        <\/p>\n        <p>\n          Termsheet business model canvas user experience churn rate low hanging fruit backing iteration buyer seed money. Virality\n          release launch party channels validation learning curve paradigm shift hypotheses conversion. Stealth leverage\n          freemium venture startup business-to-business accelerator market.\n        <\/p>\n        <blockquote>\n          Gen-z strategy long tail churn rate seed money channels user experience incubator startup partner network low hanging fruit\n          direct mailing. Client backing success startup assets responsive web design burn rate A\/B testing metrics first\n          mover advantage conversion.\n        <\/blockquote>\n        <p>\n          Freemium non-disclosure agreement lean startup bootstrapping holy grail ramen MVP iteration accelerator. Strategy market\n          ramen leverage paradigm shift seed round entrepreneur crowdfunding social proof angel investor partner network\n          virality.\n        <\/p>",
          "backdrop": "https:\/\/facebook.design\/public\/images\/an-unforgettable-valentines-day.png",
          "user_id": 1,
          "category_id": 1,
          "created_at": "2018-12-09T09:18:07Z",
          "modified_date": null,
          "status": true,
          "slug": "an-unforgettable-valentines-day-18"
        },
        {
          "id": 72,
          "heading": "How to Improve Your JavaScript Skills by Writing Your Own Web Development Framework",
          "description": "Listen to those events and update the bound property with the new value from the event. All other elements bound to the same property will update automatically thanks to the proxy.",
          "content": "<p>Have you ever asked yourself how a framework works?<\/p><p>When I discovered <a href=\"https:\/\/angularjs.org\/\" target=\"_blank\">AngularJS<\/a> after learning <a href=\"https:\/\/jquery.com\/\" target=\"_blank\">jQuery<\/a> many years ago, AngularJS seemed like dark magic to me.<\/p><p>Then Vue.js came out, and upon analyzing how it works under the hood, I was encouraged to try writing my own <a href=\"https:\/\/en.wikipedia.org\/wiki\/Data_binding\" target=\"_blank\">two-way binding system<\/a>.<\/p><p>In this article, I’ll show you how to write a modern JavaScript framework with custom HTML element attributes, reactivity, and double-binding.<\/p><p><br><\/p><h2>How does reactivity work?<\/h2><p>It would be good to start with an understanding of how reactivity works. The good news is that this is simple. Actually, when you declare a new component in Vue.js, the framework will <a href=\"https:\/\/vuejs.org\/v2\/guide\/reactivity.html#How-Changes-Are-Tracked\" target=\"_blank\">proxify each property<\/a> (getters and setters) using the <a href=\"https:\/\/en.wikipedia.org\/wiki\/Proxy_pattern\" target=\"_blank\">proxy design pattern<\/a>.<\/p><p>Thus it will be able to detect property value changes both from code and user inputs.<\/p><p><br><\/p><h2>What the proxy design pattern looks&nbsp;like<\/h2><p>The idea behind the proxy pattern is simply to overload access to an object. An analogy in real life could be the access to your bank account.<\/p><p>For example, you can’t directly access your bank account balance and change the value according to your needs. It is necessary for you to ask someone that has this permission, in this case, your bank.<\/p><p>By overloading the <code>set<\/code> function, it’s possible to manipulate its behavior. You can change the value to set, update another property instead, or even not do anything at all.<\/p><p><br><\/p><h2>Reactivity example<\/h2><p>Now that you’re confident about how the proxy design pattern works, let’s begin writting our JavaScript framework.<\/p><p>To keep it simple, we’ll mimic the AngularJS syntax to do it. Declaring a controller and binding template elements to controller properties is quite straightforward.<\/p><p>First, define a controller with properties. Then use this controller in a template. Finally, use the <code>ng-bind<\/code> attribute to enable double-binding with the element value.<\/p><p><br><\/p><h2>Parse template and instantiate the controller<\/h2><p>To have properties to bind, we need to get a place (aka controller) to declare those properties. Thus, it is necessary to define a controller and introduce it to our framework.<\/p><p>During the controller declaration, the framework will look for elements that have <code>ng-controller<\/code> attributes.<\/p><p>If it fits with one of the declared controllers, it will create a new instance of this controller. This controller instance is only responsible for this particular piece of template.<\/p>",
          "backdrop": "http:\/\/res.cloudinary.com\/dnammd7o9\/image\/upload\/v1549710423\/blog\/2019-02-09T11:07:02.171Z.jpg",
          "user_id": 3,
          "category_id": null,
          "created_at": "2019-02-09T11:07:04Z",
          "modified_date": null,
          "status": true,
          "slug": "how-to-improve-your-javascript-skills-by-writing-your-own-web-development-framework"
        }

      ]);
    });
};
